---
name: Bridgecrew  IaC Scan
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 15 7 * * 0
permissions:
  contents: read
jobs:
  prisma_cloud_iac_scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    name: Run Bridgecrew
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run Bridgecrew
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master
        with:
          api-key: ${{ secrets.BC_API_KEY }}
