jobs:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
        name: Run Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master
        with:
          # You will need Prisma Cloud API Access Token
          # More details in https://github.com/prisma-cloud-shiftleft/iac-scan-action
          api-key: ${{ secrets.BC_API_KEY }}
         
       
